environment:
  APPVEYOR_RDP_PASSWORD: tile-gtk
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: off
install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - bash -lc "pacman --needed --noconfirm -Syu"
  - bash -lc "pacman --needed --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-cmake"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-gtk2"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-glib2"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-tk"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  - set PATH=C:\msys\mingw64\bin
test_script:
  - C:\msys\mingw64\bin\cmake . -G "MinGW Makefiles"
  - C:\msys\mingw64\mingw32-make
