build: off
install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - bash -lc "pacman --needed --noconfirm -Syu"
  - bash -lc "pacman --needed --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-cmake"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-gtk2"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-glib2"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-tk"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  - cd "C:\projects\gtkttk"
  - set PATH=C:\msys\mingw64\bin
test_script:
  - cmake . -G "MinGW Makefiles"
  - mingw32-make

