environment:
  APPVEYOR_RDP_PASSWORD: rUC,QiKE%gde~SqZ
build: off
install:
  - python3 -m pip install nose scikit-build
  - set PATH=C:\msys64\usr\bin;%PATH%
  # Load PGP Keys for Msys64
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman -U --noconfirm --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  # Kill gpg-agent due to bug in MSYS
  - TaskKill /IM gpg-agent.exe /F
  # Install build dependencies
  - bash -lc "pacman --needed --noconfirm -Syu"
  - bash -lc "pacman --needed --noconfirm -Sy"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-pango"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-cmake"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-gtk2"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-glib2"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-tk"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-toolchain"
  # Now using MinGW pkg-config and related executables
  - set PATH=C:\msys64\mingw64\bin;%PATH%
test_script:
  - C:\msys64\mingw64\bin\cmake . -G "MinGW Makefiles"
  - C:\msys64\mingw64\bin\mingw32-make
  - python3 -m nose
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
