environment:
  matrix:
    - PYTHON: "C:\\PYTHON38-x64"
build: off
install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  # Load PGP Keys for Msys64
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman -U --noconfirm --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  # Kill gpg-agent due to bug in MSYS
  - TaskKill /IM gpg-agent.exe /F
  # Install build dependencies
  - bash -lc "pacman --needed --noconfirm -Syu"
  - bash -lc "pacman --needed --noconfirm -Sy"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-pango"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-cmake"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-gtk2"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-glib2"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-tk"
  - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-toolchain"
  # - bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-python3-pip"
  # Install Python build dependencies
  - "%PYTHON%\\python.exe -m pip install scikit-build nose"
  # Now using MinGW pkg-config and related executables
  - set PATH=C:\msys64\mingw64\bin;%PATH%
build_script:
  - C:\msys64\mingw64\bin\cmake . -G "MinGW Makefiles"
  - C:\msys64\mingw64\bin\mingw32-make
  - "%PYTHON%\\python.exe setup.py build"
test_script:
  - "%PYTHON%\\python.exe -m nose"
artifacts:
  - path: "/dist/*.whl"
deploy:
  provider: GitHub
  auth_token:
    secure: QimY++/91urL/oMJL/q2zYFqc1C7747HguEaIbPQovtC3zG8CK+TiCmFOCXy1D6e
  artifact: "/dist/*.whl"
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
