language: python
dist: bionic
compiler: gcc
services:
  - xvfb
addons:
  apt:
    packages:
    - libgtk2.0-dev
    - libglib2.0-dev
    - tcl-dev
    - tk-dev
install:
  - sudo apt install cmake build-essential
  - sudo -H python -m pip install nose scikit-build
script:
  - python setup.py install
  - rm -rf ./gttk
  - python -m nose
