language: python
sudo: required
dist: bionic
compiler: gcc
addons:
  apt:
    packages:
    - libgtk2.0-dev
    - libglib2.0-dev
    - tcl-dev
    - tk-dev
install:
  - sudo -H python -m pip install nose
script:
  - sudo -H python setup.py install
  - python -m nose
