language: python
sudo: required
dist: bionic
compiler: gcc

addons:
  apt:
    packages:
    - libgtk2.0-dev
    - libglib2.0-dev
    - tcl-dev
    - tk-dev

before_script:
  - cmake .
script:
  - make
  - sudo make install
